@startuml

skin rose

node "Client Computer A" as N1 {
  component "Chirp! website" as C1
}

node "Client Computer B" as N2 {
  component "Chirp! website" as C2
}

node "Azure App Server" as AAS {
  component "Chirp.Web Server" as S
}

node "Azure SQL Server" as ASS {
  component "SQL Server" as SQL
  database "SQL\ndatabase" as DB
}


() HTTP as H

C1 ..> H : use
C2 ..> H : use

H - S

S - SQL

SQL - DB

@enduml