name: .NET Build and Test

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Warsaw"

      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Pull and Run SQL Server container
        run: |
          docker pull mcr.microsoft.com/mssql/server:2022-latest
          docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=ApM5z#Afo%j&E&RL" \
             -p 1433:1433 --name mssql --hostname mssql \
             -d \
             mcr.microsoft.com/mssql/server:2022-latest
      - name: set dotnet user secrets
        run: |
          dotnet user-secrets init -p ./src/Chirp.Web
          dotnet user-secrets set "ConnectionStrings:AZURE_SQL_CONNECTIONSTRING" "Server=localhost,1433;Initial Catalog=bdsagroup5-chirpdb;Persist Security Info=False;User ID=SA;Password=ApM5z#Afo%j&E&RL;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" -p ./src/Chirp.Web
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
